site_name: Xarxes
docs_dir: md
site_dir: docs
nav:
  - Home: index.md
  - Situacions d'aprenentatge:
    - SA1 Connectoritzacio cables de pars trenats: connectoritzacioParsTrenats/ConnectoritzacioParsTrenats.md
  - Examples de codic:
    - Python: examplesCodic/python.md
  - Examples de diagrames:
    - Mermaid: Mermaid/DiagramaER.md
theme:
  name: 'material'
  features:
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - content.code.copy
    - content.code.annotate
  font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Canvia a mode oscur
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Canvia a mode clar
plugins:
  - search
  - page-to-pdf
  - with-pdf
      #author: "Juanvi Company"
      #copyright: "Creative Commons CC BY-NC-SA 4.0"
      #cover_title: "Xarxes"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path:
        - md
#extra_css:
#  - css/styles.css
#extra_templates:
#  - index.html


